name: Bug report
description: File a reproducible bug report to help us fix issues quickly.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please provide as much detail as possible so we can reproduce it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
      placeholder: Describe what happened and what you expected instead.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include a minimal reproduction when possible.
      placeholder: |
        1. Install dependencies with ...
        2. Run ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: The version of browser-sdk you are using.
      placeholder: e.g. 0.4.0
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g. 20.18.0
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS and environment
      placeholder: e.g. macOS 14.6, Ubuntu 24.04, CI, browser version
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste logs, stack traces, or screenshots if available.
      render: shell
    validations:
      required: false
