name: Feature request
description: Suggest an idea or enhancement for browser-sdk.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea.
        Please describe the problem and proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I am trying to ... but ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you want to see.
      placeholder: It would be helpful if ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options or workarounds you have considered.
      placeholder: I also considered ...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Additional context
      description: API design notes, compatibility concerns, examples, links, etc.
    validations:
      required: false
